---
- name: Configuring required DNS on IdM for OCP4 VMs and URLs
  vars:
    openshift_domain: ocp4
    openshift_routedomain: apps
    dns_a_zone: steinlab.de.
    dns_ptr_zone: 4.168.192.in-addr.arpa
    ipa_host: idm1.steinlab.de
    ipa_user: admin
    ldap_uri: ldap://idm1.steinlab.de/
    ldap_bind: uid=admin,cn=users,cn=accounts,dc=steinlab,dc=de
    ldap_dns_srv_dn: idnsname=_etcd-server-ssl._tcp.ocp4,idnsname=steinlab.de.,cn=dns,dc=steinlab,dc=de
  vars_prompt:
    - name: ipa_password
      prompt: "Please enter admin password for IdM"
      private: yes
  hosts: all
  gather_facts: false
  roles:
    - configure_idmdns
