openshift_version: 4.6
openshift_clusternet: 10.8.0.0/14
openshift_clusternetprefix: 23
openshift_servicenet: 172.30.0.0/16
openshift_domain: ocp4
openshift_routedomain: apps
network_domain: steinlab.de
ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJDfHs9cDLoZKDC9ifSqQE+GW8oMDOghvEIxOPZLTbirNvFtEveOUd0dnTh4QFFcEqsRk94gTX8vfS8lWLd8272eqmE263wsq/5mx51ugI5TDituSHCi27MtYPKroDUY+pv3lVFAvRwQw4pSSleK3iwCdOB/cqsKP5KLr3USagHNV9xWcXYWbECY6epQmgujmUxLM89vWJ4+hfEgXsst3lKJZcbE8yGVdhZt04U9i+65NOS2TQOrYCmn7MWJ5Hh31dRBDiYeojjachpocyMAuGUZkZg+wpQEhZp+/JgqC2X/Fpr2KPxsN+d1FvYkwGzQWH8h7xKhPZ2m//OGXJpsWNKLLpp2VV+WhUtR8XT9HmkamJ3RU70jya+WNemlSJ+0ZrqGIJE7Lyudu9LyxVPi6Wc8KasozkNFVwO++y3mkXh6QKqhgyN42LKm7N4MTeE6FZeZsPCAiQNpxkAwWrSlWUEATflaDnJfDgACLnV7xFGBJiGIpkRMmEepWncMvwYOZlAyGgEyg6zRqjugeVeIxbRmfHDUvclUw5s2q3nknxyyJBSTTm0cjMZZR8cCl6rfZ8ctNahx1NURXGGt1sKhep1gigHV9mnslHL1bNPSoWZSGwG9udt60UWsznIvhcz9vGEkmsQgf4FanPNmLsFU8OpTqtkHKZ1iFXuOR6/HTmmw== gab@kaiser.stein.de
